### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by jcklpe** [isacikgoz/gitbatch#61]
Hey, cool project!

I installed but have seemed to run into an error immediately. I admit I'm not the most experienced person son maybe this is super obvious. 

After installing I run gitbatch and I get an "exec format error" response. Any clue what the issue is?

**Comment by isacikgoz** [comment]
hey @jcklpe thank you! 

Can you provide more information about your environment? (OS, arch etc.)

- Did you installed it via `go get github.com/isacikgoz/gitbatch` or via [release](https://github.com/isacikgoz/gitbatch/releases) page?
- Do you have `git` installed on your system? Does command `git` works? or you aliased it to something else?

**Comment by isacikgoz** [comment]
This issue is seems to be an issue about trying to run wrong executable. I guess, you should check the executable prior to your OS and Architecture. (e.g. if you are using a 64-bit OS and x86 processor along with a Linux distro you should download gitbatch_0.4.1_linux_amd64.tar.gz)

 Since there is no feedback for almost a week I am closing this issue.

**Comment by isacikgoz** [comment]
No worries @jcklpe, I'm glad you got it working!
