### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gregf** [isacikgoz/gitbatch#84]
gitbatch: 0.4.1

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x872b19]

goroutine 1 [running]:
github.com/isacikgoz/gitbatch/gui.(*Gui).renderBranches(0xc4201a6e60, 0x0, 0x0, 0xc4202320f0)
        /home/isacikgoz/.local/share/go/src/github.com/isacikgoz/gitbatch/gui/sideviews.go:70 +0x89
github.com/isacikgoz/gitbatch/gui.(*Gui).renderSideViews(0xc4201a6e60, 0x0, 0x4, 0xc4202320f0)
        /home/isacikgoz/.local/share/go/src/github.com/isacikgoz/gitbatch/gui/sideviews.go:50 +0x5a
github.com/isacikgoz/gitbatch/gui.(*Gui).renderMain(0xc4201a6e60, 0x0, 0x0)
        /home/isacikgoz/.local/share/go/src/github.com/isacikgoz/gitbatch/gui/repositoriesview.go:29 +0x1ce
github.com/isacikgoz/gitbatch/gui.(*Gui).repositoryUpdated.func1(0xc420210000, 0x1, 0xc42011fb40)
        /home/isacikgoz/.local/share/go/src/github.com/isacikgoz/gitbatch/gui/repositoriesview.go:35 +0x2a
github.com/jroimartin/gocui.(*Gui).MainLoop(0xc420210000, 0xc420210000, 0x0)
        /home/isacikgoz/.local/share/go/src/github.com/jroimartin/gocui/gui.go:377 +0x1e0
github.com/isacikgoz/gitbatch/gui.(*Gui).Run(0xc4201a6e60, 0x0, 0x0)
        /home/isacikgoz/.local/share/go/src/github.com/isacikgoz/gitbatch/gui/gui.go:140 +0x1ee
main.run(0x0, 0x0, 0x0, 0xb13646, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/isacikgoz/git/gitbatch/main.go:52 +0x122
main.main()
        /home/isacikgoz/git/gitbatch/main.go:24 +0xc2
``

**Comment by isacikgoz** [comment]
Thanks for the feedback @gregf Can you update to the version `0.4.2`? Because if we look at the error it happens here:
https://github.com/isacikgoz/gitbatch/blob/498536a76ff9b01c8db997ce20e572a6e3c2a510/gui/sideviews.go#L70
Which, does not seem right, it is already doing a `nil` check. That means, either repo or its state is `nil`. That brings us to another question. Repositories are already initialized with a status. That means if there is a repo there must be a state. The only thing is may be there is no repository at all. 

And, there is the error. Gotcha! There is no repository loaded. That means;

1. You should run gitbatch at top folder of your repositories, not inside them. e.g. if you store your repositories at ~/git you should run gitbatch there. **Not** in ~/git/repo
2. I will apply a patch to fix this in the next release.

**Comment by gregf** [comment]
This is ran at a top level directory, below it is probably 15-20 git repos.

**Comment by gregf** [comment]
There is one svn dir in there would that screw it up possibly?

**Comment by isacikgoz** [comment]
Well, it can be. But it shouldn’t be. I will test it with a svn repo.

**Comment by isacikgoz** [comment]
I tried with a svn repo, it didn't break anything. Does it crash right in the beginning?

**Comment by gregf** [comment]
Yeah soon as I start it, anything I can do to help debug?

**Comment by isacikgoz** [comment]
I've just add a fix for crash. And it's merged to master. Please let me know if you still the issue. Also, feel free to open a new issue.

**Comment by gregf** [comment]
I just updated with go get -u and it's now fixed. Thank you!.
